# Generated by Django 3.2.8 on 2021-10-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('io_csv_plats_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='csvs',
            table='CSVs',
        ),
    ]
