# Generated by Django 3.2.8 on 2021-10-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('io_csv_plats_app', '0002_alter_csvs_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvs',
            options={'verbose_name': 'CSVs'},
        ),
    ]
