# Generated by Django 3.2.8 on 2021-10-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('io_csv_plats_app', '0003_alter_csvs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvs',
            options={'verbose_name': 'CSV'},
        ),
    ]
