# Generated by Django 3.2.8 on 2021-10-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('io_csv_plats_app', '0004_alter_csvs_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvs',
            name='activated',
        ),
    ]
